Hw02 express
AlexCheverda/goit-nodejs-hw-02-06 pull request #1
Opened 2023-02-11 09:41 UTC by AlexCheverda

Доброго дня!
Перевірте, будьласка!

2023-02-11 13:08 UTC, Eastvarga requested changes
Є зауваження

2023-02-11 13:08 UTC, Eastvarga commented on controllers/contacts/addContact.js
> +});
Схему валідації спробуйте виділити у окремий файл

2023-02-11 13:08 UTC, Eastvarga commented on controllers/contacts/addContact.js
> +    }
Цей код - валідація тіла запиту, виокремлюється у мідлвар валідації та використовується перед контроллером не повинна бути частиною контроллера

2023-02-11 13:08 UTC, Eastvarga commented on controllers/contacts/updateContactById.js
> +});
дублювання коду - тому й кажу, що треба викремити у файл та імпортувати де потрібно

2023-02-11 13:08 UTC, Eastvarga commented on controllers/contacts/updateContactById.js
> +    }
теж саме валідація не повинна бути частиною контроллера

2023-02-11 13:08 UTC, Eastvarga commented on models/contacts.js
> +  return contactById || null;
зайве - подивіться що може повертати метод пошуку - тому якщо використовуєте null лише для зіставлення, а не для повернення значення це зайве

2023-02-11 13:08 UTC, Eastvarga commented on routes/api/contacts.js
> +router.post('/', controllerWrapper(controller.addContact));
router.post('/', **createContactValidation**, controllerWrapper(controller.addContact)); - ось як використати мідлвар валідації у рауті
Сподіваюсь решту Ви зрозумієте

2023-02-12 14:24 UTC, AlexCheverda commented on controllers/contacts/addContact.js
> +});
Виніс в окремий файл

2023-02-12 14:25 UTC, AlexCheverda commented on controllers/contacts/addContact.js
> +    }
виніс у мідлвар

2023-02-12 14:26 UTC, AlexCheverda commented on controllers/contacts/updateContactById.js
> +});
Прибрав дублювання і імпортував

2023-02-12 14:26 UTC, AlexCheverda commented on controllers/contacts/updateContactById.js
> +    }
виніс у мідлвар

2023-02-12 14:28 UTC, AlexCheverda commented on models/contacts.js
> +  return contactById || null;
Прибрав 18-ий рядок

2023-02-12 14:28 UTC, AlexCheverda commented on routes/api/contacts.js
> +router.post('/', controllerWrapper(controller.addContact));
Використав мідлвар валідації

2023-02-12 14:31 UTC, AlexCheverda commented
Виправив зауваження

2023-02-12 16:50 UTC, Eastvarga requested changes
Є зауваження

2023-02-12 16:50 UTC, Eastvarga commented on models/contacts.js
> +  return contactById || null;
Ви не зрозуміли, що у  return contactById || null;  **null** зайвий. Поміркуйте над  тим чому саме.

2023-02-12 16:50 UTC, Eastvarga commented on routes/api/contacts.js
router.put('/:contactId', controllerWrapper(controller.updateContactById));
чому тут немає валідації? Забули що тут треба додати, мабуть? Будьте уважні

2023-02-12 17:19 UTC, AlexCheverda commented on routes/api/contacts.js
Дійсно неуважний. Переробив. Цього разу повинно бути вірно

2023-02-13 15:30 UTC, Eastvarga approved these changes

2023-02-13 15:30 UTC, merged