Hw05 avatars
AlexCheverda/goit-nodejs-hw-02-06 pull request #4
Opened 2023-03-01 20:34 UTC by AlexCheverda

Доброго вечора, Олександр!
Перевірте, будьласка!

2023-03-02 18:03 UTC, Eastvarga requested changes
Є зауваження

2023-03-02 18:03 UTC, Eastvarga commented on controllers/contacts/getAllContacts.js
> +            { skip, limit }).populatr("owner", "name email");
Здається тут помилка є

2023-03-02 20:06 UTC, AlexCheverda commented
Доброго вечора, Олександр!
Знайшов помилку, виправив

2023-03-03 17:22 UTC, Eastvarga approved these changes

2023-03-03 17:23 UTC, merged